INSERT INTO stocks_stock (stock_name, stock_ticker, created_at, updated_at)
VALUES
('Aarti Industries Ltd.', 'AARTIIND.NS', NOW(), NOW()),
('ABB India Ltd.', 'ABB.NS', NOW(), NOW()),
('Aditya Birla Fashion & Retail Ltd.', 'ABFRL.NS', NOW(), NOW()),
('Adani Enterprises Ltd.', 'ADANIENT.NS', NOW(), NOW()),
('Adani Enterprises Ltd.', 'ADANIENT.BO', NOW(), NOW()),
('Adani Ports & SEZ Ltd.', 'ADANIPORTS.BO', NOW(), NOW()),
('Adani Power Ltd.', 'ADANIPOWER.BO', NOW(), NOW()),
('Adani Ports & SEZ Ltd.', 'ADANIPORTS.NS', NOW(), NOW()),
('Adani Power Ltd.', 'ADANIPOWER.NS', NOW(), NOW()),
('Alkem Laboratories Ltd.', 'ALKEM.NS', NOW(), NOW()),
('Alstone Textiles', 'ALSTONE.BO', NOW(), NOW()),
('Ambuja Cements Ltd.', 'AMBUJACEM.NS', NOW(), NOW()),
('APL Apollo Tubes Ltd.', 'APLAPOLLO.NS', NOW(), NOW()),
('Apollo Hospitals Enterprise Ltd.', 'APOLLOHOSP.NS', NOW(), NOW()),
('Apollo Tyres Ltd.', 'APOLLOTYRE.NS', NOW(), NOW()),
('Arvind Ltd.', 'ARVIND.NS', NOW(), NOW()),
('Ashok Leyland Ltd.', 'ASHOKLEY.NS', NOW(), NOW()),
('Asian Paints Ltd.', 'ASIANPAINT.BO', NOW(), NOW()),
('Asian Paints Ltd.', 'ASIANPAINT.NS', NOW(), NOW()),
('Astral Ltd.', 'ASTRAL.NS', NOW(), NOW()),
('Aurobindo Pharma Ltd.', 'AUROPHARMA.NS', NOW(), NOW()),
('Avance Technologies Ltd.', 'AVANCE.BO', NOW(), NOW()),
('Axis Bank Ltd.', 'AXISBANK.NS', NOW(), NOW()),
('Bajaj Auto Ltd.', 'BAJAJ-AUTO.NS', NOW(), NOW()),
('Bajaj Finserv Ltd.', 'BAJAJFINSV.NS', NOW(), NOW()),
('Bajaj Hindusthan Ltd.', 'BAJAJHIND.NS', NOW(), NOW()),
('Bajaj Finance Ltd.', 'BAJFINANCE.NS', NOW(), NOW()),
('Balkrishna Industries Ltd.', 'BALKRISIND.NS', NOW(), NOW()),
('Balrampur Chini Mills Ltd.', 'BALRAMCHIN.NS', NOW(), NOW()),
('Bank of Baroda Ltd.', 'BANKBARODA.NS', NOW(), NOW()),
('Bank of India Ltd.', 'BANKINDIA.NS', NOW(), NOW()),
('Bharat Electronics Ltd.', 'BEL.NS', NOW(), NOW()),
('Bharat Earth Movers Ltd.', 'BEML.NS', NOW(), NOW()),
('Berg Paints Ltd.', 'BERGEPAINT.NS', NOW(), NOW()),
('Bharat Forge Ltd.', 'BHARATFORG.NS', NOW(), NOW()),
('Bharti Airtel Ltd.', 'BHARTIARTL.NS', NOW(), NOW()),
('Bharat Heavy Electricals Ltd.', 'BHEL.NS', NOW(), NOW()),
('Biocon Ltd.', 'BIOCON.NS', NOW(), NOW()),
('Bosch Ltd.', 'BOSCHLTD.NS', NOW(), NOW()),
('Bharat Petroleum Corporation Ltd.', 'BPCL.NS', NOW(), NOW()),
('Britannia Industries Ltd.', 'BRITANNIA.NS', NOW(), NOW()),
('Canara Bank Ltd.', 'CANBK.NS', NOW(), NOW()),
('Castrol India Ltd.', 'CASTROLIND.NS', NOW(), NOW()),
('Central Bank of India Ltd.', 'CENTRALBK.NS', NOW(), NOW()),
('CESC Ltd.', 'CESC.NS', NOW(), NOW()),
('Chambal Fertilizers & Chemicals Ltd.', 'CHAMBLFERT.NS', NOW(), NOW()),
('Chennai Petroleum Corporation Ltd.', 'CHENNPETRO.NS', NOW(), NOW()),
('Cholamandalam Investment and Finance Co. Ltd.', 'CHOLAFIN.NS', NOW(), NOW()),
('Cipla Ltd.', 'CIPLA.NS', NOW(), NOW()),
('Coal India Ltd.', 'COALINDIA.BO', NOW(), NOW()),
('Coal India Ltd.', 'COALINDIA.NS', NOW(), NOW()),
('Colgate-Palmolive (India) Ltd.', 'COLPAL.NS', NOW(), NOW()),
('Container Corporation of India Ltd.', 'CONCOR.NS', NOW(), NOW()),
('Coromandel International Ltd.', 'COROMANDEL.NS', NOW(), NOW()),
('CPSE ETF', 'CPSEETF.NS', NOW(), NOW()),
('Cummins India Ltd.', 'CUMMINSIND.NS', NOW(), NOW()),
('Cyient Ltd.', 'CYIENT.NS', NOW(), NOW()),
('Dabur India Ltd.', 'DABUR.NS', NOW(), NOW()),
('DCM Shriram Ltd.', 'DCMSHRIRAM.NS', NOW(), NOW()),
('Deepak Fertilizers & Petrochemicals Ltd.', 'DEEPAKFERT.NS', NOW(), NOW()),
('Divi’s Laboratories Ltd.', 'DIVISLAB.NS', NOW(), NOW()),
('DLF Ltd.', 'DLF.NS', NOW(), NOW()),
('Dr. Reddy’s Laboratories Ltd.', 'DRREDDY.NS', NOW(), NOW()),
('Edelweiss Financial Services Ltd.', 'EDELWEISS.NS', NOW(), NOW()),
('Eicher Motors Ltd.', 'EICHERMOT.NS', NOW(), NOW()),
('EID Parry India Ltd.', 'EIDPARRY.NS', NOW(), NOW()),
('Electrosteel Castings Ltd.', 'ELECTCAST.NS', NOW(), NOW()),
('Emami Ltd.', 'EMAMILTD.NS', NOW(), NOW()),
('Empower India Ltd.', 'EMPOWER.BO', NOW(), NOW()),
('Engineers India Ltd.', 'ENGINERSIN.NS', NOW(), NOW()),
('Exide Industries Ltd.', 'EXIDEIND.NS', NOW(), NOW()),
('FACT Ltd.', 'FACT.NS', NOW(), NOW()),
('FCS Software Solutions Ltd.', 'FCSSOFT.NS', NOW(), NOW()),
('Federal Bank Ltd.', 'FEDERALBNK.NS', NOW(), NOW()),
('Fortis Healthcare Ltd.', 'FORTIS.NS', NOW(), NOW()),
('Firstsource Solutions Ltd.', 'FSL.NS', NOW(), NOW()),
('GAIL (India) Ltd.', 'GAIL.NS', NOW(), NOW()),
('Ganesh Housing Corporation Ltd.', 'GANESHHOUC.NS', NOW(), NOW()),
('Genus Power Infrastructures Ltd.', 'GENUSPOWER.NS', NOW(), NOW()),
('Gillette India Ltd.', 'GILLETTE.NS', NOW(), NOW()),
('GMR Infrastructure Ltd.', 'GMRINFRA.NS', NOW(), NOW()),
('GNFC Ltd.', 'GNFC.NS', NOW(), NOW()),
('Godrej Consumer Products Ltd.', 'GODREJCP.NS', NOW(), NOW()),
('Godrej Properties Ltd.', 'GODREJPROP.NS', NOW(), NOW()),
('Goldman Sachs ETF', 'GOLDBEES.NS', NOW(), NOW()),
('Grasim Industries Ltd.', 'GRASIM.NS', NOW(), NOW()),
('Green Power Projects Ltd.', 'GREENPOWER.NS', NOW(), NOW()),
('Gujarat State Fertilizers & Chemicals Ltd.', 'GSFC.NS', NOW(), NOW()),
('GTL Infrastructure Ltd.', 'GTLINFRA.BO', NOW(), NOW()),
('GTL Infrastructure Ltd.', 'GTLINFRA.NS', NOW(), NOW()),
('Hathway Cable & Datacom Ltd.', 'HATHWAY.NS', NOW(), NOW()),
('Havells India Ltd.', 'HAVELLS.NS', NOW(), NOW()),
('HBL Power Systems Ltd.', 'HBLPOWER.NS', NOW(), NOW()),
('Hindustan Construction Company Ltd.', 'HCC.NS', NOW(), NOW()),
('HCL Technologies Ltd.', 'HCLTECH.NS', NOW(), NOW()),
('HDFC Bank Ltd.', 'HDFCBANK.NS', NOW(), NOW()),
('Heritage Foods Ltd.', 'HERITGFOOD.NS', NOW(), NOW()),
('Hero MotoCorp Ltd.', 'HEROMOTOCO.NS', NOW(), NOW()),
('HFCL Ltd.', 'HFCL.NS', NOW(), NOW()),
('Himatsingka Seide Ltd.', 'HIMATSEIDE.NS', NOW(), NOW()),
('Hindalco Industries Ltd.', 'HINDALCO.NS', NOW(), NOW()),
('Hindustan Copper Ltd.', 'HINDCOPPER.NS', NOW(), NOW()),
('Hindustan Petroleum Corporation Ltd.', 'HINDPETRO.NS', NOW(), NOW()),
('Hindustan Unilever Ltd.', 'HINDUNILVR.NS', NOW(), NOW()),
('Hindustan Zinc Ltd.', 'HINDZINC.NS', NOW(), NOW());