# Generated by Django 4.2.16 on 2025-02-16 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="updated_at",
        ),
    ]
