# Generated by Django 4.2.16 on 2025-02-16 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_remove_portfolio_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portfolio",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
