# Generated by Django 4.2.16 on 2025-02-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_portfolio_created_at_portfolio_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
