# Generated by Django 4.2.16 on 2025-03-20 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0004_alter_portfolio_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Portfolio",
        ),
    ]
