# Generated by Django 4.2.16 on 2025-02-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_is_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_customer",
            field=models.BooleanField(default=False),
        ),
    ]
