# Generated by Django 4.2.16 on 2025-02-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_is_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_customer",
            new_name="is_customerr",
        ),
    ]
