# Generated by Django 4.2.16 on 2025-02-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_is_customerr_customuser_is_customer"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Costumer",
            new_name="Customer",
        ),
    ]
